- name: Install and start Nginx
  hosts: slaves
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache (Ubuntu/Debian)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Nginx (Ubuntu/Debian)
      apt:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - name: Enable and start Nginx
      service:
        name: nginx
        state: started
        enabled: yes
